In [9]:
import numpy as np

In [10]:
np.pi

3.141592653589793

In [11]:
np.e

2.718281828459045

In [13]:
np.abs(-4535)

4535

In [15]:
a = np.array([2,3,4])

In [17]:
a[0]

2

In [19]:
a.dtype

dtype('int32')

In [37]:
arr2 = np.array([6,7,8], dtype=int)
arr2.dtype

dtype('int32')

In [40]:
mat = np.array([ 
    [1,2,3,4,5],
    [6,7,8,9,10] 
])
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [47]:
mat[0][1]

2

In [54]:
mat[:2 , :3]

array([[1, 2, 3],
       [6, 7, 8]])

In [60]:
a = np.empty([2,4]) #valores al azar
a

array([[0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000],
       [0.00000000e+000, 6.69953016e-321, 1.97345609e-312,
        0.00000000e+000]])

In [62]:
b = np.zeros([5,5])
b

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [63]:
c = np.ones([5,5])
c

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [65]:
d = np.identity(10)
d

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [66]:
d.shape

(10, 10)

In [68]:
np.ones(d.shape)

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [71]:
np.linspace(0,20, num=13)

array([ 0.        ,  1.66666667,  3.33333333,  5.        ,  6.66666667,
        8.33333333, 10.        , 11.66666667, 13.33333333, 15.        ,
       16.66666667, 18.33333333, 20.        ])

In [73]:
bc = np.arange(8)
bc

array([0, 1, 2, 3, 4, 5, 6, 7])

In [76]:
mat.reshape([5,2])

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [79]:
mat2 = np.array([ [1,2,3,4,5],[2,3,4,5,6] ])
mat3 = np.array([ [1,4,3,5,2],[2,4,4,5,6] ])
mat2 < mat3

array([[False,  True, False,  True, False],
       [False,  True, False, False, False]])